# Generated by Django 5.2.4 on 2025-10-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_kitchen', '0002_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
