# Generated by Django 5.2.4 on 2025-10-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_kitchen', '0004_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
