# Generated by Django 5.2.4 on 2025-10-17 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_kitchen', '0005_user_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('starters', 'Starters & Snacks'), ('main_course', 'Main Course'), ('biryani', 'Biryani & Rice'), ('burgers', 'Burgers & Fast Food'), ('drinks', 'Drinks & Beverages'), ('desserts', 'Desserts & Ice Creams'), ('combos', 'Combos & Meal Boxes')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('icon_class', models.CharField(help_text="FontAwesome icon class (e.g., 'fas fa-hamburger')", max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='cloud_kitchen.category')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
