# Generated by Django 5.2.4 on 2025-10-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_kitchen', '0009_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_offer_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
